theme: jekyll-theme-slate
title: Ewen Lavoie
description: PhD Candidate at the University of Alberta thinking about VR, Embodiment, and Consciousness
photo: https://github.com/uboat87/uboat87.github.io/blob/main/SC63%20cropped.jpg
