theme: jekyll-theme-slate
title: Ewen Lavoie
description: MD Class of 2024 at the University of Calgary
description: PhD Candidate at the University of Alberta
description: Thinking about VR, Embodiment, and Consciousness
email: elavoie@ualberta.ca
twitter_username: EwenLavoie
linkedin_username:  EwenLavoie
