theme: jekyll-theme-slate
title: Ewen Lavoie, MD PhD
description: Physical Medicine and Rehabilitation Resident Physician at the University of Alberta
email: elavoie@ualberta.ca
twitter_username: EwenLavoie
linkedin_username:  EwenLavoie
