theme: jekyll-theme-slate
title: Ewen Lavoie
description: PhD Candidate at the University of Alberta thinking about VR, Embodiment, and Consciousness [CV](https://github.com/uboat87/uboat87.github.io/raw/main/LavoieEwen_CVAcademic_January2021.pdf) [GoogleScholar](https://scholar.google.com/citations?user=2j_adCsAAAAJ&hl=en&authuser=1) [Twitter](https://twitter.com/ewenlavoie) [LinkedIn](https://www.linkedin.com/in/ewenlavoie/) <elavoie@ualberta.ca>
